# F5 VIP Provisioning Workflow - Quarkus Configuration

quarkus.rest-client.f5_openapi_yaml.url=${F5_HOST:http://mock-workflow-backends:8080}
quarkus.rest-client.connectivity_openapi_yaml.url=${CONNECTIVITY_HOST:http://mock-workflow-backends:8080}
quarkus.rest-client.servicenow_openapi_yaml.url=${SERVICENOW_URL:http://mock-workflow-backends:8080}

# Kogito / Data-Index eventing
kogito.events.processdefinitions.enabled=true
kogito.events.processinstances.enabled=true
mp.messaging.outgoing.kogito-processdefinitions-events.url=${KOGITO_DATAINDEX_URL:http://sonataflow-platform-data-index-service}/definitions
mp.messaging.outgoing.kogito-processinstances-events.url=${KOGITO_DATAINDEX_URL:http://sonataflow-platform-data-index-service}/processes
kogito.service.url=${KOGITO_SERVICE_URL:http://f5-vip-provisioning.sonataflow-infra.svc.cluster.local:8080}
