# Branch Outage Response Workflow - Quarkus Configuration

quarkus.rest-client.servicenow_openapi_yaml.url=${SERVICENOW_URL:http://mock-workflow-backends:8080}
quarkus.rest-client.teams_openapi_yaml.url=${TEAMS_WEBHOOK_URL:http://mock-workflow-backends:8080}
quarkus.rest-client.sms_openapi_yaml.url=${SMS_SERVICE_URL:http://mock-workflow-backends:8080}

# Kogito / Data-Index eventing
kogito.events.processdefinitions.enabled=true
kogito.events.processinstances.enabled=true
mp.messaging.outgoing.kogito-processdefinitions-events.url=${KOGITO_DATAINDEX_URL:http://sonataflow-platform-data-index-service}/definitions
mp.messaging.outgoing.kogito-processinstances-events.url=${KOGITO_DATAINDEX_URL:http://sonataflow-platform-data-index-service}/processes
kogito.service.url=${KOGITO_SERVICE_URL:http://branch-outage-response.sonataflow-infra.svc.cluster.local:8080}
